import Head from "next/head";
import DescriptionContent from "../components/DescriptionContent";
import Hero from "../components/Hero";
import Instagram from "../components/Instagram";
import Navbar from "../components/Navbar";
import Releases from "../components/Releases";
import Sections from "../components/Sections";
import Slider from "../components/Slider";
import FooterContent from "../components/FooterContent";
import { SliderData } from "../components/SliderData";
import HeroDescription from "../components/HeroDescription";

function Home({ posts }) {

  return (
    <div>
		<Head>
			<title>Photography Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<Navbar header={posts.data.header} />
		<Hero
			heading="Captur Photography"
			message="Más que un par de zapatos, es cultura, historia y tradición."
		/>
		<Sections />
		<Releases />
		<DescriptionContent />
		
		<HeroDescription
			content="It's a team-based strategy game where two teams of five powerful champions face off to destroy the other’s base. Choose from over 140 champions to make epic plays, secure kills, and take down towers as you battle your way to victory."
			category="Blog"
			title="Nuestra historia como artesanos"
			url="#"
			videoSrc="https://player.vimeo.com/external/474375164.sd.mp4?s=18d69af509cf8e20802cb3c5ee3d1f85f386f7b0&profile_id=164&oauth2_token_id=57447761"
			left
		/>

		<Instagram />
		<FooterContent />

		{/**
		<hr />
		<h1 className="text-6xl text-sz-dark">Somos Zapateros</h1>
		<h2 className="text-5xl text-sz-gray">Somos Zapateros</h2>
		<h3 className="text-4xl text-sz-brown-light">Somos Zapateros</h3>
		<h4 className="text-3xl text-sz-brown">Somos Zapateros</h4>
		<h5 className="text-2xl text-sz-brown-dark">Somos Zapateros</h5>

		<Slider slides={SliderData} />
		 */}
    </div>
  );
}

export async function getStaticProps() {
	const res = await fetch(
		"https://tienda.somoszapateros.com/wp-json/rae/v1/header-footer?header_location_id=hcms-menu-header&footer_location_id=hcms-menu-footer"
	);
	const posts = await res.json();
  
	return {
		props: {
			posts,
		},
	};
}

export default Home;
