import Head from "next/head";
import Navbar from "../components/Navbar";
import Releases from "../components/Releases";
import FooterContent from "../components/FooterContent";

function Tienda({ posts }) {

  return (
    <div>
		<Head>
			<title>Photography Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<Navbar header={posts.data.header} />

		<FooterContent />

		{/**
		<hr />
		<h1 className="text-6xl text-sz-dark">Somos Zapateros</h1>
		<h2 className="text-5xl text-sz-gray">Somos Zapateros</h2>
		<h3 className="text-4xl text-sz-brown-light">Somos Zapateros</h3>
		<h4 className="text-3xl text-sz-brown">Somos Zapateros</h4>
		<h5 className="text-2xl text-sz-brown-dark">Somos Zapateros</h5>
		 */}
    </div>
  );
}

export async function getStaticProps() {
	const res = await fetch(
		"https://tienda.somoszapateros.com/wp-json/rae/v1/header-footer?header_location_id=hcms-menu-header&footer_location_id=hcms-menu-footer"
	);
	const posts = await res.json();
  
	return {
		props: {
			posts,
		},
	};
}

export default Tienda;
