import Head from "next/head";
import Navbar from "../components/Navbar";
import FooterContent from "../components/FooterContent";
import Products from "../components/Products";

function Tienda({ posts, dataProducts }) {
    const products = dataProducts.products || []

	return (
		<div>
			<Head>
				<title>Photography Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar header={posts.data.header} />

			<Products products={products} />

			<FooterContent />
		</div>
	);
}

export async function getStaticProps() {
	const res = await fetch('https://tienda.somoszapateros.com/wp-json/rae/v1/header-footer?header_location_id=hcms-menu-header&footer_location_id=hcms-menu-footer');
    const resProducts = await fetch('http://localhost:3000/api/get-products')
	
    const posts = await res.json();
    const dataProducts = await resProducts.json()
    
	return {
		props: {
			posts,
            dataProducts,
		},
	};
}

export default Tienda;
